[package]
name = "otap-df-admin-api"
description = "Public admin API and SDK for the OTAP dataflow engine"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = ["http-client", "crypto-ring"]
http-client = ["dep:async-trait", "dep:reqwest"]
crypto-ring = ["otap-df-crypto/crypto-ring"]
crypto-aws-lc = ["otap-df-crypto/crypto-aws-lc"]
crypto-openssl = ["otap-df-crypto/crypto-openssl"]
crypto-symcrypt = ["otap-df-crypto/crypto-symcrypt"]

[dependencies]
otap-df-admin-types = { workspace = true }
otap-df-config = { workspace = true }
otap-df-crypto = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

async-trait = { workspace = true, optional = true }
reqwest = { version = "0.13.1", default-features = false, features = ["rustls-no-provider", "json", "query", "http2"], optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net", "io-util", "time"] }
wiremock = { workspace = true }
otap-test-tls-certs = { workspace = true }
rustls = { workspace = true }
rustls-pki-types = { workspace = true }
tempfile = { workspace = true }
tokio-rustls = { workspace = true }
